/**
 * Language Context - AfroPlan
 * Système de traduction multi-langues
 * Langues supportées: FR, EN, DE, ES
 */

import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Types
export type Language = 'fr' | 'en' | 'de' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
  languages: { code: Language; name: string; flag: string }[];
}

// Available languages
const LANGUAGES = [
  { code: 'fr' as Language, name: 'Français', flag: '🇫🇷' },
  { code: 'en' as Language, name: 'English', flag: '🇬🇧' },
  { code: 'de' as Language, name: 'Deutsch', flag: '🇩🇪' },
  { code: 'es' as Language, name: 'Español', flag: '🇪🇸' },
];

// Translations
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.next': 'Suivant',
    'common.back': 'Retour',
    'common.search': 'Rechercher',
    'common.attention': 'Attention',
    'common.seeAll': 'Voir tout',
    'common.seeResults': 'Voir les résultats',
    'common.results': 'résultats',
    'common.noResults': 'Aucun résultat trouvé',
    'common.refresh': 'Actualiser',
    'common.refreshResults': 'Actualisation des résultats...',
    'common.distance': 'Distance',
    'common.rating': 'Note',
    'common.price': 'Prix',

    // Explore
    'explore.searchPlaceholder': 'Coiffeur, salon, style...',
    'explore.filters': 'Filtres',
    'explore.map': 'Carte',
    'explore.list': 'Liste',
    'explore.applyFilters': 'Appliquer les filtres',
    'explore.resetFilters': 'Réinitialiser',
    'explore.advancedFilters': 'Filtres avancés',
    'explore.minRating': 'Note minimale',
    'explore.priceRange': 'Fourchette de prix',
    'explore.locationType': 'Lieu de la prestation',
    'explore.both': 'Les deux',
    'explore.onlyPromos': 'Uniquement les promos',
    'explore.resultsFor': 'résultats pour',

    // Quick Filters
    'QUICK_FILTERS.rated': 'Mieux notés',
    'QUICK_FILTERS.available': 'Disponibles',

    // Salon Detail
    'salon.about': 'À propos',
    'salon.services': 'Services',
    'salon.reviews': 'Avis',
    'salon.address': 'Adresse',
    'salon.bookNow': 'Réserver maintenant',
    'salon.openingHours': 'Horaires d\'ouverture',
    'salon.contact': 'Contact',
    'salon.noServices': 'Aucun service disponible pour le moment.',
    'salon.noReviews': 'Aucun avis pour le moment.',
    'salon.verified': 'Vérifié',
    'salon.call': 'Appeler',
    'salon.share': 'Partager',
    'salon.directions': 'Itinéraire',
    'salon.gallery': 'Galerie',
    'salon.stylists': 'Coiffeurs',
    'salon.selectService': 'Choisissez vos services',
    'salon.selectedServices': 'services sélectionnés',
    'salon.totalPrice': 'Total',
    'salon.book': 'Continuer',
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.logout': 'Déconnexion',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.noAccount': 'Pas de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.loginRequired': 'Connexion requise',
    'auth.loginRequiredMessage': 'Vous devez être connecté pour effectuer un paiement.',
    'common.errorOccurred': 'Une erreur est survenue. Veuillez réessayer.',

    // Home
    'home.welcome': 'Bienvenue sur AfroPlan',
    'home.hello': 'Bonjour',
    'home.readyForHairstyle': 'Disponible pour une nouvelle coiffure ?',
    'home.featured': 'À la une',
    'home.hairstyleCategories': 'Catégories de coiffures',
    'home.seeLess': 'Voir moins',
    'home.searchSalon': 'Rechercher mon salon / coiffeur',
    'home.searchSubtitle': 'Trouve le style qui te correspond',
    'home.promotions': 'Offres du moment',
    'home.hairstyles': 'Styles de coiffure',
    'home.nearbyCoiffeurs': 'Coiffeurs à proximité',
    'home.popularSalons': 'Salons populaires',
    'home.tipsAndInspiration': 'Conseils & Inspiration',
    'home.areYouCoiffeur': 'Tu es coiffeur(se) ?',
    'home.joinAfroPlanPro': 'Rejoins AfroPlan Pro et développe ton activité',
    'home.discoverPro': 'Découvrir AfroPlan Pro',

    // Search Flow
    'search.findCoiffeur': 'Trouve facilement ton coiffeur afro',
    'search.quickQuestions': 'Quelques questions rapides pour te proposer les meilleurs salons adaptés à tes besoins.',
    'search.chooseStyle': 'Choisis ta coiffure',
    'search.chooseCategory': 'Choisis ta catégorie',
    'search.whatTypeHairstyle': 'Quel type de coiffure cherches-tu ?',
    'search.step': 'Étape',
    'search.of': 'sur',
    'search.backAtAnyTime': 'Tu peux revenir en arrière à tout moment',
    'search.locationTemporarilyDisabled': 'Localisation désactivée (temporairement)',
    'search.whatStyle': 'Quel style te ferait plaisir ?',
    'search.quickFilter': 'Filtre rapide',
    'search.optional': 'Optionnel - Affine ta recherche',
    'search.hairType': 'Type de cheveux',
    'search.whereCoiffeur': 'Où souhaites-tu te faire coiffer ?',
    'search.inSalon': 'En salon',
    'search.atHome': 'À domicile',
    'search.goToSalon': 'Se déplacer au salon',
    'search.coiffeurComesHome': 'Le coiffeur vient chez vous',
    'search.budgetDistance': 'Budget & Distance',
    'search.maxBudget': 'Budget maximum',
    'search.maxDistance': 'Distance maximum',
    'search.showAllSalons': 'Je veux voir tous les salons (ignorer les filtres)',
    'search.paymentInfo': 'Tu pourras choisir de payer le montant total ou un acompte lors de la réservation.',
    'search.canGoBack': 'Tu peux revenir en arrière à tout moment',
    'search.quickPay': 'Paiement rapide',

    // Reservations
    'booking.myReservations': 'Mes réservations',
    'booking.loginMessage': 'Connectez-vous pour voir vos rendez-vous',
    'booking.noUpcoming': 'Aucun rendez-vous à venir',
    'booking.noPast': 'Aucun rendez-vous passé',
    'booking.exploreSalons': 'Explorer les salons',
    'booking.discoverSalonsMessage': 'Découvrez nos salons et prenez rendez-vous !',
    'booking.cancelImpossible': 'Annulation impossible',
    'booking.cancelImpossibleMessage': 'Ce rendez-vous a été validé par un acompte. Pour toute modification ou annulation, veuillez contacter directement le salon. L\'acompte n\'est pas remboursable via l\'application.',
    'booking.cancelAndRefund': 'Annuler et rembourser ?',
    'booking.cancelPenaltyMessage': 'Conformément à nos conditions, une pénalité de 20% s\'applique pour toute annulation d\'une prestation payée d\'avance.',
    'booking.amountPaid': 'Montant payé',
    'booking.cancelFee': 'Frais d\'annulation',
    'booking.amountRefunded': 'Montant qui vous sera remboursé',
    'booking.keepAppt': 'Conserver mon RDV',
    'booking.confirmCancel': 'Confirmer l\'annulation',
    'booking.cancelSuccess': 'Votre rendez-vous a été annulé.',
    'booking.cancelRefundProcessing': 'Votre remboursement est en cours de traitement.',
    'booking.cancelAppt': 'Annuler le rendez-vous',
    'booking.cancelConfirmMessage': 'Voulez-vous vraiment annuler ce rendez-vous ? Cette action est immédiate et gratuite car aucun paiement n\'a été effectué.',
    'booking.cancelFinalSuccess': 'Votre rendez-vous a été définitivement supprimé.',
    'booking.deleteError': 'Impossible de supprimer le rendez-vous.',
    'booking.noEdit': 'Ce rendez-vous ne peut plus être modifié.',
    'booking.cancelReason': 'Motif d\'annulation',
    'booking.unavailable': 'Indisponible',
    'booking.noPhone': 'Le salon n\'a pas renseigné de numéro de téléphone.',
    'booking.incompleteAddress': 'L\'adresse du salon est incomplète.',

    // Chat
    'chat.writeMessage': 'Écrivez votre message...',
    'chat.online': 'En ligne',
    'chat.reservationConfirmed': 'Réservation confirmée ! Vous pouvez maintenant discuter.',
    'chat.willBeLate': "J'aurai un peu de retard",
    'chat.onMyWay': 'Je suis en route',
    'chat.whatTime': 'À quelle heure exactement ?',
    'chat.sendAddress': "Pouvez-vous m'envoyer l'adresse ?",

    // Coiffeur Dashboard
    'coiffeur.dashboard': 'Tableau de bord',
    'coiffeur.weeklyRevenue': 'Revenus de la semaine',
    'coiffeur.weeklyAppt': 'RDV/sem.',
    'coiffeur.today': 'Aujourd\'hui',
    'coiffeur.rating': 'Note',
    'coiffeur.activity': 'Activité',
    'coiffeur.estimatedNet': 'Revenus (Net estimé)',
    'coiffeur.total': 'Total',
    'coiffeur.fees': 'Frais',
    'coiffeur.net': 'Net',
    'coiffeur.proActions': 'Actions professionnelles',
    'coiffeur.flashBoost': 'Boost Flash',
    'coiffeur.manualAppt': 'RDV Manuel',
    'coiffeur.manualApptTitle': 'Nouveau RDV Manuel',
    'coiffeur.manualApptDesc': 'Enregistrez un rendez-vous pris hors application pour bloquer votre créneau.',
    'coiffeur.clientName': 'Nom du client',
    'coiffeur.service': 'Prestation',
    'coiffeur.yourServices': 'VOS PRESTATIONS',
    'coiffeur.date': 'Date',
    'coiffeur.time': 'Heure',
    'coiffeur.saveAppt': 'Enregistrer le rendez-vous',
    'coiffeur.flashBoostTitle': 'Boost de dernière minute 🚀',
    'coiffeur.flashBoostDesc': 'Voulez-vous activer une promotion flash de -15% sur tous vos services pour les prochaines 4 heures ? Cela aidera à remplir vos créneaux vides.',
    'coiffeur.later': 'Plus tard',
    'coiffeur.activateBoost': 'Activer le Boost',
    'coiffeur.boostActivated': 'Boost activé !',
    'coiffeur.boostActivatedDesc': 'Votre promotion est en ligne et vos clients favoris ont été notifiés.',
    'coiffeur.clientMode': 'Mode Client',
    'coiffeur.bookService': 'Réserver une prestation',
    'coiffeur.readyToLaunch': 'Prêt à lancer votre salon ?',
    'coiffeur.setupShowcase': 'Configurez votre vitrine pour recevoir vos premiers clients.',
    'coiffeur.createSalon': 'Créer mon salon',
    'coiffeur.restrictedAccess': 'Accès restreint',
    'coiffeur.init': 'Initialisation...',
    'coiffeur.all': 'Toutes',
    'coiffeur.pending': 'En attente',
    'coiffeur.confirmed': 'Confirmées',
    'coiffeur.blockDay': 'Bloquer ma journée (Urgence)',
    'coiffeur.unblockDay': 'Débloquer ma journée',
    'coiffeur.noReservations': 'Aucune réservation',
    'coiffeur.reservationsAppear': 'Les réservations apparaîtront ici',
    'coiffeur.paymentMethod': 'Mode de paiement',
    'coiffeur.paidOnline': 'Payé en ligne',
    'coiffeur.remainingAtSalon': 'Reste à payer au salon',
    'coiffeur.total': 'Total',
    'coiffeur.confirm': 'Confirmer',
    'coiffeur.cancel': 'Annuler',
    'coiffeur.message': 'Message',
    'coiffeur.validated': 'Rendez-vous validé',
    'coiffeur.confirmTitle': 'Confirmer la réservation',
    'coiffeur.confirmDesc': 'Voulez-vous confirmer cette réservation et informer le client ?',
    'coiffeur.confirmSuccess': 'Le rendez-vous a été confirmé et le message de bienvenue a été envoyé.',
    'coiffeur.cancelTitle': 'Annuler le rendez-vous',
    'coiffeur.cancelWarning': 'Attention : Soyez bienveillant et professionnel dans votre explication. Votre réponse impacte directement l\'image de votre salon.',
    'coiffeur.cancelReasonLabel': 'Raison de l\'annulation (le client recevra ce message) :',
    'coiffeur.cancelReasonPlaceholder': 'Ex: Urgence personnelle, fatigue excessive, pause imprévue...',
    'coiffeur.keepAppt': 'Conserver le rendez-vous',
    'coiffeur.confirmCancel': 'Confirmer l\'annulation',
    'coiffeur.refundNote': '* Le client sera remboursé automatiquement de la totalité du montant payé en ligne (hors frais Stripe).',
    'coiffeur.blockDayConfirm': 'Êtes-vous sûr de vouloir fermer toutes vos réservations en ligne pour aujourd\'hui ? Plus aucun client ne pourra réserver de créneau.',
    'coiffeur.unblockDayConfirm': 'Voulez-vous rouvrir vos réservations en ligne pour aujourd\'hui ?',
    'coiffeur.blockSuccess': 'Votre journée a été bloquée. Plus aucun rendez-vous ne pourra être pris en ligne pour aujourd\'hui.',
    'coiffeur.unblockSuccess': 'Vos réservations pour aujourd\'hui sont à nouveau ouvertes !',
    'coiffeur.cancelSuccess': 'Le client a été informé de la raison et le remboursement a été initié automatiquement.',
    'coiffeur.myStyles': 'Mes styles',
    'coiffeur.catalog': 'Catalogue',
    'coiffeur.myPrestations': 'Mes prestations',
    'coiffeur.loadingPrestations': 'Chargement de vos prestations...',
    'coiffeur.catalogHint': 'Cochez tous les styles que vous proposez, puis cliquez sur le bouton de configuration en bas.',
    'coiffeur.alreadyConfigured': 'Déjà configuré',
    'coiffeur.addOtherPrestations': 'Ajouter d\'autres prestations',
    'coiffeur.boostBookings': 'Boostez vos réservations ! 🚀',
    'coiffeur.boostBookingsDesc': 'Les coiffeurs avec leurs propres photos reçoivent en moyenne 3x plus de demandes.',
    'coiffeur.noPrestation': 'Aucune prestation',
    'coiffeur.noPrestationDesc': 'Allez dans le catalogue et cochez les styles que vous maîtrisez',
    'coiffeur.viewCatalog': 'Voir le catalogue',
    'coiffeur.removeStyle': 'Retirer ce style',
    'coiffeur.removeStyleConfirm': 'Voulez-vous retirer ce style de vos prestations ?',
    'coiffeur.remove': 'Retirer',
    'coiffeur.publishSalonNow': 'PUBLIER MON SALON MAINTENANT',
    'coiffeur.servicesRequiredToPublish': 'SERVICES REQUIS POUR PUBLIER',
    'coiffeur.salonOnline': 'SALON EN LIGNE',
    'coiffeur.unpublish': 'Dépublier',
    'coiffeur.unpublishTitle': 'Retirer de la publication ?',
    'coiffeur.unpublishDesc': 'Votre salon ne sera plus visible.',
    'coiffeur.unpublishSuccess': 'Votre salon est hors ligne.',
    'coiffeur.configStyles': 'Configurer les styles',
    'coiffeur.configStyle': 'Configurer le style',
    'coiffeur.configTitle': 'Configuration',
    'coiffeur.configIntro': 'Définissez vos tarifs, durées et ajoutez une photo pour chaque style.',
    'coiffeur.realPhoto': 'Photo réelle de votre travail',
    'coiffeur.catalogPhoto': 'Photo catalogue (remplacez-la !)',
    'coiffeur.priceEuro': 'Prix (€)',
    'coiffeur.durationMin': 'Durée (min)',
    'coiffeur.location': 'Lieu',
    'coiffeur.noteOptional': 'Note ou précision (optionnel)',
    'coiffeur.saveSuccess': 'style(s) configuré(s) et sauvegardé(s).',
    'coiffeur.publishTitle': 'Publier votre salon',
    'coiffeur.publishDesc': 'Votre salon sera visible par tous les clients AfroPlan. Souhaitez-vous continuer ?',
    'coiffeur.publishCongrat': 'Félicitations ! 🎉',
    'coiffeur.publishCongratDesc': 'Votre salon est désormais en ligne et prêt à recevoir des réservations.',
    'coiffeur.managePrices': 'Gérer mes tarifs',
    'coiffeur.photoPrestation': 'Photo de la prestation',
    'coiffeur.choosePhotoSource': 'Comment souhaitez-vous ajouter la photo ?',
    'coiffeur.takePhoto': 'Prendre une photo',
    'coiffeur.chooseFromGallery': 'Choisir dans la galerie',
    'coiffeur.developActivity': 'Développez votre activité',
    'coiffeur.joinCommunity': 'Rejoignez la communauté AfroPlan Pro et boostez votre salon',
    'coiffeur.rdvManagement': 'Gestion des RDV',
    'coiffeur.manageReservations': 'Gérez facilement vos réservations',
    'coiffeur.moreClients': 'Plus de clients',
    'coiffeur.increaseVisibility': 'Augmentez votre visibilité',
    'coiffeur.statistics': 'Statistiques',
    'coiffeur.trackPerformance': 'Suivez vos performances',
    'coiffeur.payments': 'Paiements',
    'coiffeur.securePayment': 'Encaissez en toute sécurité',
    'coiffeur.readyToStart': 'Prêt à commencer ?',
    'coiffeur.registerFree': 'Inscrivez-vous gratuitement et commencez à recevoir des réservations',
    'coiffeur.createProAccount': 'Créer mon compte Pro',
    'coiffeur.needPhotoHelp': 'Besoin d\'aide pour vos photos ?',
    'coiffeur.photoHelpDesc': 'Si vous avez des difficultés pour des prises de photos professionnelles, contactez-nous et nous viendrons vous aider gratuitement !',

    // Favorites
    'fav.favorites': 'Favoris',
    'fav.favoritesSubtitle': 'Vos salons et styles préférés',
    'fav.yourFavorites': 'Vos favoris',
    'fav.loginMessage': 'Connectez-vous pour sauvegarder vos salons et styles préférés',
    'fav.salons': 'Salons',
    'fav.styles': 'Styles',
    'fav.noFavorites': 'Aucun favori pour le moment',
    'fav.removeSuccess': 'Retiré des favoris',
    'profile.settings': 'Paramètres',
    'profile.language': 'Langue',
    'profile.notifications': 'Notifications',
    'profile.help': 'Aide',
    'profile.about': 'À propos',
    'profile.rdv': 'RDV',
    'profile.salons': 'Salons',
    'profile.spent': 'Dépensé',
    'profile.modeCoiffeur': 'Mode Coiffeur',
    'profile.switchToCoiffeur': 'Basculer vers l\'espace coiffeur',
    'profile.recentBookings': 'Mes rendez-vous récents',
    'profile.seeAll': 'Tout voir',
    'profile.noRecentBookings': 'Aucun rendez-vous récent',
    'profile.messagesAlerts': 'Messages & Alertes',
    'profile.myConversations': 'Mes conversations',
    'profile.myConversationsDesc': 'Échanges avec vos coiffeurs',
    'profile.notificationsDesc': 'Historique de vos alertes',
    'profile.account': 'Compte',
    'profile.editProfile': 'Modifier le profil',
    'profile.editProfileDesc': 'Nom, photo, informations',
    'profile.settingsDesc': 'Langue, sécurité',
    'profile.helpSupport': 'Aide & Support',
    'profile.logout': 'Se déconnecter',
    'profile.editProfileTitle': 'Modifier mon profil',
    'profile.fullName': 'Nom complet',
    'profile.phone': 'Téléphone',
    'profile.saveChanges': 'Enregistrer les modifications',
    'profile.appLanguage': 'Langue de l\'application',
    'profile.preferences': 'Préférences',
    'profile.pushNotifications': 'Notifications Push',
    'profile.darkMode': 'Mode Sombre automatique',
    'profile.user': 'Utilisateur',
    'profile.logoutConfirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',

    // Hairstyles
    'hairstyle.tresses': 'Tresses',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Coupe',
    'hairstyle.soins': 'Soins',
    'hairstyle.coloration': 'Coloration',
    'hairstyle.tissage': 'Tissage',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',

    // Role selection
    'role.chooseSpace': 'Choisissez votre espace',
    'role.clientSpace': 'Espace Client',
    'role.clientSubtitle': 'Trouve ton coiffeur afro et réserve en quelques clics',
    'role.coiffeurSpace': 'Espace Coiffeur',
    'role.coiffeurSubtitle': 'Gère tes rendez-vous et développe ton activité',
    'role.start': 'Commencer',
    'role.access': 'Accéder',
    'role.tagline': 'La coiffure afro, réinventée.',
    'role.trust': 'Déjà +100 coiffeurs nous font confiance.',
    'role.switchRole': 'Changer de parcours',
    'role.switchToClient': 'Passer en mode Client',
    'role.switchToCoiffeur': 'Passer en mode Coiffeur',

    // Onboarding
    'onboarding.slide1Title': 'Des coiffeurs passionnés',
    'onboarding.slide1Subtitle': 'Spécialistes des cheveux afro près de chez toi',
    'onboarding.slide2Title': 'Trouve ton style parfait',
    'onboarding.slide2Subtitle': 'Des centaines de coiffures afro à portée de main',
    'onboarding.slide3Title': 'Réserve en quelques clics',
    'onboarding.slide3Subtitle': 'Simple, rapide et sans stress',
    'onboarding.touchToContinue': 'Touchez l\'écran pour continuer',

    // Geolocation
    'geo.enableLocation': 'Activer la géolocalisation',
    'geo.locationDesc': 'Pour trouver les salons près de chez toi',
    'geo.permissionDenied': 'Permission de localisation refusée',
    'geo.maxDistance': 'Distance maximum',
    'geo.nearbyRadius': 'Rayon de recherche',

    // Checkout & Payment
    'checkout.title': 'Paiement',
    'checkout.secure': 'Sécurisé',
    'checkout.yourBooking': 'Votre réservation',
    'checkout.paymentMethod': 'Moyen de paiement',
    'checkout.creditCard': 'Carte bancaire',
    'checkout.priceDetail': 'Détail du prix',
    'checkout.servicePrice': 'Prix du service',
    'checkout.depositNow': 'Acompte à payer maintenant',
    'checkout.depositInfo': 'Cet acompte confirme votre réservation et sera déduit du prix total. Le reste sera payé directement au salon le jour du rendez-vous.',
    'checkout.remainingAtSalon': 'Reste à payer au salon',
    'checkout.securePayment': 'Paiement sécurisé en 2 étapes',
    'checkout.step1': 'Payez l\'acompte maintenant',
    'checkout.step2': 'Réglez le reste au salon',
    'checkout.payDeposit': 'Payer l\'acompte de',
    'checkout.payFull': 'Payer la totalité',
    'checkout.paymentSuccess': 'Paiement réussi !',
    'checkout.paymentSuccessDesc': 'Votre réservation est confirmée.',
    'checkout.paymentError': 'Erreur de paiement',
    'checkout.paymentErrorDesc': 'Une erreur est survenue. Veuillez réessayer.',
    'checkout.viewBooking': 'Voir ma réservation',
    'checkout.termsNotice': 'Paiement sécurisé par Stripe. En payant, vous acceptez nos conditions d\'utilisation.',
    'checkout.choosePaymentType': 'Choisir le type de paiement',
    'checkout.depositOnly': 'Acompte uniquement',
    'checkout.fullPayment': 'Paiement intégral',
    'checkout.commission': 'Commission AfroPlan',

    // Salon Registration
    'salon.photos': 'Photos du salon',
    'salon.addPhotos': 'Ajoutez jusqu\'à 4 photos de votre salon',
    'salon.info': 'Informations du salon',
    'salon.name': 'Nom du salon',
    'salon.description': 'Description',
    'salon.phone': 'Téléphone',
    'salon.email': 'Email',
    'salon.emailHint': 'L\'email est celui de votre compte et ne peut pas être modifié',
    'salon.location': 'Localisation',
    'salon.address': 'Adresse',
    'salon.city': 'Ville',
    'salon.postalCode': 'Code postal',
    'salon.specialties': 'Spécialités de coiffure afro',
    'salon.selectedSpecialties': 'sélectionnées',
    'salon.save': 'Enregistrer les modifications',
    'salon.saving': 'Enregistrement...',
    'salon.saved': 'Salon enregistré !',
    'salon.savedDesc': 'Les informations de votre salon ont été sauvegardées.',
    'salon.openingHours': 'Horaires d\'ouverture',
    'salon.homeService': 'Service à domicile',
    'salon.homeServiceDesc': 'Proposez-vous un service à domicile ?',
    'salon.homeServiceFee': 'Frais de déplacement',
    'salon.connectLogin': 'Se connecter',
    'salon.createPro': 'Créer un compte Pro',

    // Extensions
    'service.requiresExtensions': 'Mèches nécessaires',
    'service.extensionsIncluded': 'Mèches fournies par le salon',
    'service.extensionsNotIncluded': 'Mèches non fournies',
    'service.extensionsNoteIncluded': 'Mèches incluses : Le coiffeur fournit les mèches.',
    'service.extensionsNoteNotIncluded': 'Mèches non fournies : Vous devez apporter vos propres mèches.',
    'service.manageExtensions': 'Gestion des mèches / extensions',
    'service.extensionsDesc': 'Indique si cette coiffure nécessite des extensions',
    'service.extensionsIncludedDesc': 'Désactivez si la cliente doit apporter ses propres mèches',
  },

  en: {
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.next': 'Next',
    'common.back': 'Back',
    'common.search': 'Search',
    'common.seeAll': 'See all',
    'common.seeResults': 'See results',

    'common.errorOccurred': 'An error occurred. Please try again.',

    // Auth
    'auth.login': 'Login',
    'auth.register': 'Sign up',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.loginRequired': 'Login required',
    'auth.loginRequiredMessage': 'You must be logged in to make a payment.',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': 'No account?',
    'auth.hasAccount': 'Already have an account?',

    // Home
    'home.welcome': 'Welcome to AfroPlan',
    'home.hello': 'Hello',
    'home.readyForHairstyle': 'Available for a new hairstyle?',
    'home.featured': 'Featured Salons',
    'home.hairstyleCategories': 'Hairstyle Categories',
    'home.seeLess': 'See less',
    'home.searchSalon': 'Search my salon / hairstylist',
    'home.searchSubtitle': 'Find the style that suits you',
    'home.promotions': 'Current offers',
    'home.hairstyles': 'Hairstyles',
    'home.nearbyCoiffeurs': 'Nearby hairstylists',
    'home.popularSalons': 'Popular salons',
    'home.tipsAndInspiration': 'Tips & Inspiration',
    'home.areYouCoiffeur': 'Are you a hairstylist?',
    'home.joinAfroPlanPro': 'Join AfroPlan Pro and grow your business',
    'home.discoverPro': 'Discover AfroPlan Pro',

    // Search Flow
    'search.findCoiffeur': 'Easily find your afro hairstylist',
    'search.quickQuestions': 'A few quick questions to suggest the best salons for your needs.',
    'search.chooseStyle': 'Choose your hairstyle',
    'search.chooseCategory': 'Choose your category',
    'search.whatTypeHairstyle': 'What type of hairstyle are you looking for?',
    'search.step': 'Step',
    'search.of': 'of',
    'search.backAtAnyTime': 'You can go back at any time',
    'search.locationTemporarilyDisabled': 'Location temporarily disabled',
    'search.whatStyle': 'What style would you like?',
    'search.quickFilter': 'Quick filter',
    'search.optional': 'Optional - Refine your search',
    'search.hairType': 'Hair type',
    'search.whereCoiffeur': 'Where would you like to get your hair done?',
    'search.inSalon': 'In salon',
    'search.atHome': 'At home',
    'search.goToSalon': 'Go to the salon',
    'search.coiffeurComesHome': 'The hairstylist comes to you',
    'search.budgetDistance': 'Budget & Distance',
    'search.maxBudget': 'Maximum budget',
    'search.maxDistance': 'Maximum distance',
    'search.showAllSalons': 'I want to see all salons (ignore filters)',
    'search.paymentInfo': 'You can choose to pay the full amount or a deposit when booking.',
    'search.canGoBack': 'You can go back at any time',
    'search.quickPay': 'Quick pay',

    // Booking
    'booking.book': 'Book',
    'booking.confirmed': 'Confirmed',
    'booking.pending': 'Pending',
    'booking.cancelled': 'Cancelled',
    'booking.completed': 'Completed',
    'booking.yourBookings': 'My bookings',
    'booking.upcoming': 'Upcoming',
    'booking.past': 'Past',

    // Chat
    'chat.writeMessage': 'Write your message...',
    'chat.online': 'Online',
    'chat.reservationConfirmed': 'Booking confirmed! You can now chat.',
    'chat.willBeLate': "I'll be a bit late",
    'chat.onMyWay': "I'm on my way",
    'chat.whatTime': 'What time exactly?',
    'chat.sendAddress': 'Can you send me the address?',

    // Coiffeur Dashboard
    'coiffeur.developActivity': 'Grow your business',
    'coiffeur.joinCommunity': 'Join the AfroPlan Pro community and boost your salon',
    'coiffeur.rdvManagement': 'Booking management',
    'coiffeur.manageReservations': 'Easily manage your bookings',
    'coiffeur.moreClients': 'More clients',
    'coiffeur.increaseVisibility': 'Increase your visibility',
    'coiffeur.statistics': 'Statistics',
    'coiffeur.trackPerformance': 'Track your performance',
    'coiffeur.payments': 'Payments',
    'coiffeur.securePayment': 'Get paid securely',
    'coiffeur.readyToStart': 'Ready to start?',
    'coiffeur.registerFree': 'Sign up for free and start receiving bookings',
    'coiffeur.createProAccount': 'Create my Pro account',
    'coiffeur.needPhotoHelp': 'Need help with your photos?',
    'coiffeur.photoHelpDesc': 'If you have trouble taking professional photos, contact us and we\'ll come help you for free!',

    // Profile
    'profile.myProfile': 'My profile',
    'profile.settings': 'Settings',
    'profile.language': 'Language',
    'profile.notifications': 'Notifications',
    'profile.help': 'Help',
    'profile.about': 'About',
    'profile.rdv': 'Appt',
    'profile.salons': 'Salons',
    'profile.spent': 'Spent',
    'profile.modeCoiffeur': 'Stylist Mode',
    'profile.switchToCoiffeur': 'Switch to stylist space',
    'profile.recentBookings': 'My recent appointments',
    'profile.seeAll': 'See all',
    'profile.noRecentBookings': 'No recent appointments',
    'profile.messagesAlerts': 'Messages & Alerts',
    'profile.myConversations': 'My conversations',
    'profile.myConversationsDesc': 'Chats with your stylists',
    'profile.notificationsDesc': 'Your alerts history',
    'profile.account': 'Account',
    'profile.editProfile': 'Edit profile',
    'profile.editProfileDesc': 'Name, photo, information',
    'profile.settingsDesc': 'Language, security',
    'profile.helpSupport': 'Help & Support',
    'profile.logout': 'Logout',
    'profile.editProfileTitle': 'Edit my profile',
    'profile.fullName': 'Full name',
    'profile.phone': 'Phone',
    'profile.saveChanges': 'Save changes',
    'profile.appLanguage': 'App language',
    'profile.preferences': 'Preferences',
    'profile.pushNotifications': 'Push Notifications',
    'profile.darkMode': 'Automatic Dark Mode',
    'profile.user': 'User',
    'profile.logoutConfirm': 'Are you sure you want to log out?',

    // Hairstyles
    'hairstyle.tresses': 'Braids',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Cut',
    'hairstyle.soins': 'Care',
    'hairstyle.coloration': 'Coloring',
    'hairstyle.tissage': 'Weave',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',

    // Role selection
    'role.chooseSpace': 'Choose your space',
    'role.clientSpace': 'Client Space',
    'role.clientSubtitle': 'Find your afro hairstylist and book in a few clicks',
    'role.coiffeurSpace': 'Hairstylist Space',
    'role.coiffeurSubtitle': 'Manage your appointments and grow your business',
    'role.start': 'Get started',
    'role.access': 'Access',
    'role.tagline': 'Afro hairstyling, reinvented.',
    'role.trust': 'Already 100+ hairstylists trust us.',
    'role.switchRole': 'Switch path',
    'role.switchToClient': 'Switch to Client mode',
    'role.switchToCoiffeur': 'Switch to Hairstylist mode',

    // Onboarding
    'onboarding.slide1Title': 'Passionate hairstylists',
    'onboarding.slide1Subtitle': 'Afro hair specialists near you',
    'onboarding.slide2Title': 'Find your perfect style',
    'onboarding.slide2Subtitle': 'Hundreds of afro hairstyles at your fingertips',
    'onboarding.slide3Title': 'Book in a few clicks',
    'onboarding.slide3Subtitle': 'Simple, fast and stress-free',
    'onboarding.touchToContinue': 'Tap to continue',

    // Geolocation
    'geo.enableLocation': 'Enable location',
    'geo.locationDesc': 'To find salons near you',
    'geo.permissionDenied': 'Location permission denied',
    'geo.maxDistance': 'Maximum distance',
    'geo.nearbyRadius': 'Search radius',

    // Checkout & Payment
    'checkout.title': 'Payment',
    'checkout.secure': 'Secure',
    'checkout.yourBooking': 'Your booking',
    'checkout.paymentMethod': 'Payment method',
    'checkout.creditCard': 'Credit card',
    'checkout.priceDetail': 'Price detail',
    'checkout.servicePrice': 'Service price',
    'checkout.depositNow': 'Deposit to pay now',
    'checkout.depositInfo': 'This deposit confirms your booking and will be deducted from the total price. The rest is paid directly at the salon on appointment day.',
    'checkout.remainingAtSalon': 'Remaining to pay at salon',
    'checkout.securePayment': 'Secure 2-step payment',
    'checkout.step1': 'Pay the deposit now',
    'checkout.step2': 'Pay the rest at the salon',
    'checkout.payDeposit': 'Pay deposit of',
    'checkout.payFull': 'Pay in full',
    'checkout.paymentSuccess': 'Payment successful!',
    'checkout.paymentSuccessDesc': 'Your booking is confirmed.',
    'checkout.paymentError': 'Payment error',
    'checkout.paymentErrorDesc': 'An error occurred. Please try again.',
    'checkout.viewBooking': 'View my booking',
    'checkout.termsNotice': 'Secure payment by Stripe. By paying, you accept our terms of use.',
    'checkout.choosePaymentType': 'Choose payment type',
    'checkout.depositOnly': 'Deposit only',
    'checkout.fullPayment': 'Full payment',
    'checkout.commission': 'AfroPlan commission',

    // Salon Registration
    'salon.photos': 'Salon photos',
    'salon.addPhotos': 'Add up to 4 photos of your salon',
    'salon.info': 'Salon information',
    'salon.name': 'Salon name',
    'salon.description': 'Description',
    'salon.phone': 'Phone',
    'salon.email': 'Email',
    'salon.emailHint': 'Email is from your account and cannot be changed',
    'salon.location': 'Location',
    'salon.address': 'Address',
    'salon.city': 'City',
    'salon.postalCode': 'Postal code',
    'salon.specialties': 'Afro hairstyling specialties',
    'salon.selectedSpecialties': 'selected',
    'salon.save': 'Save changes',
    'salon.saving': 'Saving...',
    'salon.saved': 'Salon saved!',
    'salon.savedDesc': 'Your salon information has been saved.',
    'salon.openingHours': 'Opening hours',
    'salon.homeService': 'Home service',
    'salon.homeServiceDesc': 'Do you offer home service?',
    'salon.homeServiceFee': 'Travel fee',
    'salon.connectLogin': 'Log in',
    'salon.createPro': 'Create Pro account',

    // Extensions
    'service.requiresExtensions': 'Extensions required',
    'service.extensionsIncluded': 'Extensions provided by salon',
    'service.extensionsNotIncluded': 'Extensions not provided',
    'service.extensionsNoteIncluded': 'Extensions included: The hairstylist provides the extensions.',
    'service.extensionsNoteNotIncluded': 'Extensions not included: You must bring your own extensions.',
    'service.manageExtensions': 'Manage extensions',
    'service.extensionsDesc': 'Indicate if this hairstyle requires extensions',
    'service.extensionsIncludedDesc': 'Disable if the client must bring their own extensions',
  },

  de: {
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.next': 'Weiter',
    'common.back': 'Zurück',
    'common.search': 'Suchen',
    'common.seeAll': 'Alle anzeigen',
    'common.seeResults': 'Ergebnisse anzeigen',
    'common.results': 'Ergebnisse',
    'common.noResults': 'Keine Ergebnisse gefunden',
    'common.sortBy': 'Sortieren nach',
    'common.distance': 'Entfernung',
    'common.rating': 'Bewertung',
    'common.price': 'Preis',

    // Explore
    'explore.searchPlaceholder': 'Friseur, Salon, Stil...',
    'explore.filters': 'Filter',
    'explore.map': 'Karte',
    'explore.list': 'Liste',
    'explore.applyFilters': 'Filter anwenden',
    'explore.resetFilters': 'Zurücksetzen',
    'explore.advancedFilters': 'Erweiterte Filter',
    'explore.minRating': 'Mindestbewertung',
    'explore.priceRange': 'Preisspanne',
    'explore.locationType': 'Dienstleistungsort',
    'explore.both': 'Beide',
    'explore.onlyPromos': 'Nur Angebote',
    'explore.resultsFor': 'Ergebnisse für',

    // Quick Filters
    'QUICK_FILTERS.rated': 'Top bewertet',
    'QUICK_FILTERS.available': 'Verfügbar',

    // Salon Detail
    'salon.about': 'Über',
    'salon.services': 'Dienstleistungen',
    'salon.reviews': 'Bewertungen',
    'salon.address': 'Adresse',
    'salon.bookNow': 'Jetzt buchen',
    'salon.openingHours': 'Öffnungszeiten',
    'salon.contact': 'Kontakt',
    'salon.noServices': 'Zur Zeit keine Dienstleistungen verfügbar.',
    'salon.noReviews': 'Noch keine Bewertungen.',
    'salon.verified': 'Verifiziert',
    'salon.call': 'Anrufen',
    'salon.share': 'Teilen',
    'salon.directions': 'Anfahrt',
    'salon.gallery': 'Galerie',
    'salon.stylists': 'Friseure',
    'salon.selectService': 'Wählen Sie Ihre Dienste',
    'salon.selectedServices': 'Dienste ausgewählt',
    'salon.totalPrice': 'Gesamt',
    'salon.book': 'Weiter',
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.logout': 'Abmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.noAccount': 'Kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',

    // Home
    'home.welcome': 'Willkommen bei AfroPlan',
    'home.hello': 'Hallo',
    'home.readyForHairstyle': 'Bereit für eine neue Frisur?',
    'home.featured': 'Empfohlene Salons',
    'home.hairstyleCategories': 'Frisuren-Kategorien',
    'home.seeLess': 'Weniger anzeigen',
    'home.searchSalon': 'Meinen Salon / Friseur suchen',
    'home.searchSubtitle': 'Finde den Stil, der zu dir passt',
    'home.promotions': 'Aktuelle Angebote',
    'home.hairstyles': 'Frisuren',
    'home.nearbyCoiffeurs': 'Friseure in der Nähe',
    'home.popularSalons': 'Beliebte Salons',
    'home.tipsAndInspiration': 'Tipps & Inspiration',
    'home.areYouCoiffeur': 'Bist du Friseur(in)?',
    'home.joinAfroPlanPro': 'Tritt AfroPlan Pro bei und entwickle dein Geschäft',
    'home.discoverPro': 'AfroPlan Pro entdecken',

    // Search Flow
    'search.findCoiffeur': 'Finde einfach deinen Afro-Friseur',
    'search.quickQuestions': 'Ein paar schnelle Fragen, um dir die besten Salons vorzuschlagen.',
    'search.chooseStyle': 'Wähle deine Frisur',
    'search.chooseCategory': 'Wähle deine Kategorie',
    'search.whatTypeHairstyle': 'Welche Art von Frisur suchst du?',
    'search.step': 'Schritt',
    'search.of': 'von',
    'search.backAtAnyTime': 'Du kannst jederzeit zurückgehen',
    'search.locationTemporarilyDisabled': 'Standort vorübergehend deaktiviert',
    'search.whatStyle': 'Welchen Stil möchtest du?',
    'search.quickFilter': 'Schnellfilter',
    'search.optional': 'Optional - Suche verfeinern',
    'search.hairType': 'Haartyp',
    'search.whereCoiffeur': 'Wo möchtest du frisiert werden?',
    'search.inSalon': 'Im Salon',
    'search.atHome': 'Zu Hause',
    'search.goToSalon': 'Zum Salon gehen',
    'search.coiffeurComesHome': 'Der Friseur kommt zu dir',
    'search.budgetDistance': 'Budget & Entfernung',
    'search.maxBudget': 'Maximales Budget',
    'search.maxDistance': 'Maximale Entfernung',
    'search.showAllSalons': 'Ich möchte alle Salons sehen (Filter ignorieren)',
    'search.paymentInfo': 'Du kannst bei der Buchung wählen, ob du den vollen Betrag oder eine Anzahlung bezahlen möchtest.',
    'search.canGoBack': 'Du kannst jederzeit zurückgehen',
    'search.quickPay': 'Schnellzahlung',

    // Booking
    'booking.book': 'Buchen',
    'booking.confirmed': 'Bestätigt',
    'booking.pending': 'Ausstehend',
    'booking.cancelled': 'Storniert',
    'booking.completed': 'Abgeschlossen',
    'booking.yourBookings': 'Meine Buchungen',
    'booking.upcoming': 'Bevorstehend',
    'booking.past': 'Vergangen',

    // Chat
    'chat.writeMessage': 'Schreibe deine Nachricht...',
    'chat.online': 'Online',
    'chat.reservationConfirmed': 'Buchung bestätigt! Ihr könnt jetzt chatten.',
    'chat.willBeLate': 'Ich werde etwas später sein',
    'chat.onMyWay': 'Ich bin unterwegs',
    'chat.whatTime': 'Um wie viel Uhr genau?',
    'chat.sendAddress': 'Kannst du mir die Adresse schicken?',

    // Coiffeur Dashboard
    'coiffeur.developActivity': 'Entwickle dein Geschäft',
    'coiffeur.joinCommunity': 'Tritt der AfroPlan Pro Community bei und steigere deinen Salon',
    'coiffeur.rdvManagement': 'Terminverwaltung',
    'coiffeur.manageReservations': 'Verwalte deine Buchungen einfach',
    'coiffeur.moreClients': 'Mehr Kunden',
    'coiffeur.increaseVisibility': 'Steigere deine Sichtbarkeit',
    'coiffeur.statistics': 'Statistiken',
    'coiffeur.trackPerformance': 'Verfolge deine Leistung',
    'coiffeur.payments': 'Zahlungen',
    'coiffeur.securePayment': 'Sicher bezahlt werden',
    'coiffeur.readyToStart': 'Bereit loszulegen?',
    'coiffeur.registerFree': 'Registriere dich kostenlos und beginne Buchungen zu erhalten',
    'coiffeur.createProAccount': 'Mein Pro-Konto erstellen',
    'coiffeur.needPhotoHelp': 'Brauchst du Hilfe mit deinen Fotos?',
    'coiffeur.photoHelpDesc': 'Wenn du Schwierigkeiten hast, professionelle Fotos zu machen, kontaktiere uns und wir kommen kostenlos helfen!',

    // Profile
    'profile.myProfile': 'Mein Profil',
    'profile.settings': 'Einstellungen',
    'profile.language': 'Sprache',
    'profile.notifications': 'Benachrichtigungen',
    'profile.help': 'Hilfe',
    'profile.about': 'Über',
    'profile.rdv': 'Termine',
    'profile.salons': 'Salons',
    'profile.spent': 'Ausgegeben',
    'profile.modeCoiffeur': 'Friseur-Modus',
    'profile.switchToCoiffeur': 'Zum Friseur-Bereich wechseln',
    'profile.recentBookings': 'Meine letzten Termine',
    'profile.seeAll': 'Alle ansehen',
    'profile.noRecentBookings': 'Keine letzten Termine',
    'profile.messagesAlerts': 'Nachrichten & Alarme',
    'profile.myConversations': 'Meine Gespräche',
    'profile.myConversationsDesc': 'Chats mit Ihren Friseuren',
    'profile.notificationsDesc': 'Ihre Alarm-Historie',
    'profile.account': 'Konto',
    'profile.editProfile': 'Profil bearbeiten',
    'profile.editProfileDesc': 'Name, Foto, Informationen',
    'profile.settingsDesc': 'Sprache, Sicherheit',
    'profile.helpSupport': 'Hilfe & Support',
    'profile.logout': 'Abmelden',
    'profile.editProfileTitle': 'Mein Profil bearbeiten',
    'profile.fullName': 'Vollständiger Name',
    'profile.phone': 'Telefon',
    'profile.saveChanges': 'Änderungen speichern',
    'profile.appLanguage': 'App-Sprache',
    'profile.preferences': 'Präferenzen',
    'profile.pushNotifications': 'Push-Benachrichtigungen',
    'profile.darkMode': 'Automatischer Dunkelmodus',
    'profile.user': 'Benutzer',
    'profile.logoutConfirm': 'Sind Sie sicher, dass Sie sich abmelden möchten?',

    // Hairstyles
    'hairstyle.tresses': 'Zöpfe',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Schnitt',
    'hairstyle.soins': 'Pflege',
    'hairstyle.coloration': 'Färbung',
    'hairstyle.tissage': 'Weave',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',
  },

  es: {
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.next': 'Siguiente',
    'common.back': 'Atrás',
    'common.search': 'Buscar',
    'common.seeResults': 'Ver resultados',
    'common.results': 'resultados',
    'common.noResults': 'No se encontraron resultados',
    'common.sortBy': 'Ordenar por',
    'common.distance': 'Distancia',
    'common.rating': 'Calificación',
    'common.price': 'Precio',

    // Explore
    'explore.searchPlaceholder': 'Peluquero, salón, estilo...',
    'explore.filters': 'Filtros',
    'explore.map': 'Mapa',
    'explore.list': 'Lista',
    'explore.applyFilters': 'Aplicar filtros',
    'explore.resetFilters': 'Restablecer',
    'explore.advancedFilters': 'Filtros avanzados',
    'explore.minRating': 'Calificación mínima',
    'explore.priceRange': 'Rango de precios',
    'explore.locationType': 'Lugar del servicio',
    'explore.both': 'Ambos',
    'explore.onlyPromos': 'Solo promociones',
    'explore.resultsFor': 'resultados para',

    // Quick Filters
    'QUICK_FILTERS.rated': 'Mejor valorados',
    'QUICK_FILTERS.available': 'Disponibles',

    // Salon Detail
    'salon.about': 'Acerca de',
    'salon.services': 'Servicios',
    'salon.reviews': 'Avisos',
    'salon.address': 'Dirección',
    'salon.bookNow': 'Reservar ahora',
    'salon.openingHours': 'Horario de apertura',
    'salon.contact': 'Contacto',
    'salon.noServices': 'No hay servicios disponibles por el momento.',
    'salon.noReviews': 'Aún no hay avisos.',
    'salon.verified': 'Verificado',
    'salon.call': 'Llamar',
    'salon.share': 'Compartir',
    'salon.directions': 'Cómo llegar',
    'salon.gallery': 'Galería',
    'salon.stylists': 'Peluqueros',
    'salon.selectService': 'Elige tus servicios',
    'salon.selectedServices': 'servicios seleccionados',
    'salon.totalPrice': 'Total',
    'salon.book': 'Continuar',
    'auth.login': 'Iniciar sesión',
    'auth.register': 'Registrarse',
    'auth.logout': 'Cerrar sesión',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',

    // Home
    'home.welcome': 'Bienvenido a AfroPlan',
    'home.hello': 'Hola',
    'home.readyForHairstyle': '¿Disponible para un nuevo peinado?',
    'home.featured': 'Salones destacados',
    'home.hairstyleCategories': 'Categorías de peinados',
    'home.seeLess': 'Ver menos',
    'home.searchSalon': 'Buscar mi salón / estilista',
    'home.searchSubtitle': 'Encuentra el estilo que te queda',
    'home.promotions': 'Ofertas actuales',
    'home.hairstyles': 'Estilos de peinado',
    'home.nearbyCoiffeurs': 'Estilistas cercanos',
    'home.popularSalons': 'Salones populares',
    'home.tipsAndInspiration': 'Consejos e Inspiración',
    'home.areYouCoiffeur': '¿Eres estilista?',
    'home.joinAfroPlanPro': 'Únete a AfroPlan Pro y haz crecer tu negocio',
    'home.discoverPro': 'Descubrir AfroPlan Pro',

    // Search Flow
    'search.findCoiffeur': 'Encuentra fácilmente tu estilista afro',
    'search.quickQuestions': 'Algunas preguntas rápidas para sugerirte los mejores salones.',
    'search.chooseStyle': 'Elige tu peinado',
    'search.whatStyle': '¿Qué estilo te gustaría?',
    'search.quickFilter': 'Filtro rápido',
    'search.optional': 'Opcional - Refina tu búsqueda',
    'search.hairType': 'Tipo de cabello',
    'search.whereCoiffeur': '¿Dónde te gustaría peinarte?',
    'search.inSalon': 'En el salón',
    'search.atHome': 'A domicilio',
    'search.goToSalon': 'Ir al salón',
    'search.coiffeurComesHome': 'El estilista viene a ti',
    'search.budgetDistance': 'Presupuesto y Distancia',
    'search.maxBudget': 'Presupuesto máximo',
    'search.maxDistance': 'Distancia máxima',
    'search.showAllSalons': 'Quiero ver todos los salones (ignorar filtros)',
    'search.paymentInfo': 'Puedes elegir pagar el monto total o un anticipo al reservar.',
    'search.canGoBack': 'Puedes volver atrás en cualquier momento',

    // Booking
    'booking.book': 'Reservar',
    'booking.confirmed': 'Confirmado',
    'booking.pending': 'Pendiente',
    'booking.cancelled': 'Cancelado',
    'booking.completed': 'Completado',
    'booking.yourBookings': 'Mis reservas',
    'booking.upcoming': 'Próximas',
    'booking.past': 'Pasadas',

    // Chat
    'chat.writeMessage': 'Escribe tu mensaje...',
    'chat.online': 'En línea',
    'chat.reservationConfirmed': '¡Reserva confirmada! Ya pueden chatear.',
    'chat.willBeLate': 'Llegaré un poco tarde',
    'chat.onMyWay': 'Estoy en camino',
    'chat.whatTime': '¿A qué hora exactamente?',
    'chat.sendAddress': '¿Puedes enviarme la dirección?',

    // Coiffeur Dashboard
    'coiffeur.developActivity': 'Haz crecer tu negocio',
    'coiffeur.joinCommunity': 'Únete a la comunidad AfroPlan Pro y potencia tu salón',
    'coiffeur.rdvManagement': 'Gestión de citas',
    'coiffeur.manageReservations': 'Gestiona fácilmente tus reservas',
    'coiffeur.moreClients': 'Más clientes',
    'coiffeur.increaseVisibility': 'Aumenta tu visibilidad',
    'coiffeur.statistics': 'Estadísticas',
    'coiffeur.trackPerformance': 'Sigue tu rendimiento',
    'coiffeur.payments': 'Pagos',
    'coiffeur.securePayment': 'Cobra de forma segura',
    'coiffeur.readyToStart': '¿Listo para empezar?',
    'coiffeur.registerFree': 'Regístrate gratis y empieza a recibir reservas',
    'coiffeur.createProAccount': 'Crear mi cuenta Pro',
    'coiffeur.needPhotoHelp': '¿Necesitas ayuda con tus fotos?',
    'coiffeur.photoHelpDesc': 'Si tienes dificultades para tomar fotos profesionales, ¡contáctanos y te ayudaremos gratis!',

    // Profile
    'profile.myProfile': 'Mi perfil',
    'profile.settings': 'Configuración',
    'profile.language': 'Idioma',
    'profile.notifications': 'Notificaciones',
    'profile.help': 'Ayuda',
    'profile.about': 'Acerca de',
    'profile.rdv': 'Citas',
    'profile.salons': 'Salones',
    'profile.spent': 'Gastado',
    'profile.modeCoiffeur': 'Modo Peluquero',
    'profile.switchToCoiffeur': 'Cambiar al espacio peluquero',
    'profile.recentBookings': 'Mis citas recientes',
    'profile.seeAll': 'Ver todo',
    'profile.noRecentBookings': 'Sin citas recientes',
    'profile.messagesAlerts': 'Mensajes y Alertas',
    'profile.myConversations': 'Mis conversaciones',
    'profile.myConversationsDesc': 'Chats con tus peluqueros',
    'profile.notificationsDesc': 'Tu historial de alertas',
    'profile.account': 'Cuenta',
    'profile.editProfile': 'Editar perfil',
    'profile.editProfileDesc': 'Nombre, foto, información',
    'profile.settingsDesc': 'Idioma, seguridad',
    'profile.helpSupport': 'Ayuda y Soporte',
    'profile.logout': 'Cerrar sesión',
    'profile.editProfileTitle': 'Editar mi perfil',
    'profile.fullName': 'Nombre completo',
    'profile.phone': 'Teléfono',
    'profile.saveChanges': 'Guardar cambios',
    'profile.appLanguage': 'Idioma de la aplicación',
    'profile.preferences': 'Preferencias',
    'profile.pushNotifications': 'Notificaciones Push',
    'profile.darkMode': 'Modo oscuro automático',
    'profile.user': 'Usuario',
    'profile.logoutConfirm': '¿Estás seguro de que deseas cerrar sesión?',

    // Hairstyles
    'hairstyle.tresses': 'Trenzas',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Corte',
    'hairstyle.soins': 'Tratamientos',
    'hairstyle.coloration': 'Coloración',
    'hairstyle.tissage': 'Tejido',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',
  },
};

const LANGUAGE_STORAGE_KEY = '@afroplan_language';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr');

  // Load saved language on mount
  useEffect(() => {
    loadSavedLanguage();
  }, []);

  const loadSavedLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLanguage && ['fr', 'en', 'de', 'es'].includes(savedLanguage)) {
        setLanguageState(savedLanguage as Language);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        languages: LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
