/**
 * Language Context - AfroPlan
 * Système de traduction multi-langues
 * Langues supportées: FR, EN, DE, ES
 *
 * - Détecte automatiquement la langue du téléphone au premier lancement
 * - Persiste le choix via AsyncStorage
 * - Fournit la fonction t() pour traduire toutes les chaînes de l'app
 */

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform, NativeModules } from 'react-native';

// Types
export type Language = 'fr' | 'en' | 'de' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string, params?: Record<string, string | number>) => string;
  languages: { code: Language; name: string; flag: string }[];
  isReady: boolean;
}

// Available languages
const LANGUAGES = [
  { code: 'fr' as Language, name: 'Français', flag: '🇫🇷' },
  { code: 'en' as Language, name: 'English', flag: '🇬🇧' },
  { code: 'de' as Language, name: 'Deutsch', flag: '🇩🇪' },
  { code: 'es' as Language, name: 'Español', flag: '🇪🇸' },
];

// ---------------------------------------------------------------------------
// Détection de la langue du téléphone
// ---------------------------------------------------------------------------
function getDeviceLocale(): Language {
  try {
    let locale = 'fr';

    if (Platform.OS === 'ios') {
      locale =
        NativeModules.SettingsManager?.settings?.AppleLocale ||
        NativeModules.SettingsManager?.settings?.AppleLanguages?.[0] ||
        'fr';
    } else if (Platform.OS === 'android') {
      locale = NativeModules.I18nManager?.localeIdentifier || 'fr';
    }

    const lang = locale.substring(0, 2).toLowerCase();
    if (['fr', 'en', 'de', 'es'].includes(lang)) {
      return lang as Language;
    }
  } catch {
    // Silencieux
  }
  return 'fr';
}

// ---------------------------------------------------------------------------
// Traductions
// ---------------------------------------------------------------------------
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.next': 'Suivant',
    'common.back': 'Retour',
    'common.search': 'Rechercher',
    'common.seeAll': 'Voir tout',
    'common.seeLess': 'Voir moins',
    'common.seeResults': 'Voir les résultats',
    'common.add': 'Ajouter',
    'common.errorOccurred': 'Une erreur est survenue. Veuillez réessayer.',
    'common.available': 'Dispo',
    'common.open': 'Ouvert',
    'common.closed': 'Fermé',
    'common.verified': 'Vérifié',
    'common.results': 'résultat(s)',
    'common.found': 'trouvé(s)',
    'common.both': 'Les deux',
    'common.reset': 'Réinitialiser',
    'common.support': 'Support',
    'common.terms': 'CGU',
    'common.privacy': 'Confidentialité',
    'common.joinUs': 'Rejoignez-nous',
    'common.copyright': '© 2025 AfroPlan. Tous droits réservés.',
    'common.today': "Aujourd'hui",
    'common.pending': 'En attente',
    'common.confirmed': 'Confirmé',
    'common.start': 'Commencer',
    'common.newMessages': '{count} nouveaux',
    'common.warning': 'Attention',

    // Auth
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.logout': 'Déconnexion',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.noAccount': 'Pas de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.loginRequired': 'Connexion requise',
    'auth.loginRequiredMessage': 'Vous devez être connecté pour effectuer un paiement.',
    'auth.loginRequiredBooking': 'Vous devez être connecté pour réserver.',
    'auth.loginRequiredFavorite': 'Vous devez être connecté pour ajouter aux favoris.',
    'auth.loginToSee': 'Connectez-vous pour voir les détails du salon et réserver',
    'auth.createAccount': 'Créer un compte',
    'auth.logoutConfirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'auth.logoutAction': 'Déconnecter',

    // Home
    'home.welcome': 'Bienvenue sur AfroPlan',
    'home.hello': 'Bonjour {name}',
    'home.readyForHairstyle': 'Prêt(e) pour une nouvelle coiffure ?',
    'home.searchSalon': 'Rechercher mon salon / coiffeur',
    'home.searchSubtitle': 'Trouve le style qui te correspond',
    'home.promotions': 'Offres du moment',
    'home.hairstyles': 'Styles de coiffure',
    'home.nearbyCoiffeurs': 'Coiffeurs à proximité',
    'home.popularSalons': 'Salons populaires',
    'home.tipsAndInspiration': 'Conseils & Inspiration',
    'home.areYouCoiffeur': 'Tu es coiffeur(se) ?',
    'home.joinAfroPlanPro': 'Rejoins AfroPlan Pro et développe ton activité',
    'home.discoverPro': 'Découvrir AfroPlan Pro',

    // Search Flow
    'search.findCoiffeur': 'Trouve facilement ton coiffeur afro',
    'search.quickQuestions': 'Quelques questions rapides pour te proposer les meilleurs salons adaptés à tes besoins.',
    'search.chooseStyle': 'Choisis ta coiffure',
    'search.whatStyle': 'Quel style te ferait plaisir ?',
    'search.quickFilter': 'Filtre rapide',
    'search.optional': 'Optionnel - Affine ta recherche',
    'search.hairType': 'Type de cheveux',
    'search.whereCoiffeur': 'Où souhaites-tu te faire coiffer ?',
    'search.inSalon': 'En salon',
    'search.atHome': 'À domicile',
    'search.goToSalon': 'Se déplacer au salon',
    'search.coiffeurComesHome': 'Le coiffeur vient chez vous',
    'search.budgetDistance': 'Budget & Distance',
    'search.maxBudget': 'Budget maximum',
    'search.maxDistance': 'Distance maximum',
    'search.showAllSalons': 'Je veux voir tous les salons (ignorer les filtres)',
    'search.paymentInfo': 'Tu pourras choisir de payer le montant total ou un acompte lors de la réservation.',
    'search.canGoBack': 'Tu peux revenir en arrière à tout moment',
    'search.quickPay': 'Paiement rapide',
    'search.placeholder': 'Salon, coiffeur, style...',
    'search.title': 'Recherche',
    'search.advancedFilters': 'Filtres avancés',
    'search.maxDistanceLabel': 'Distance maximum',
    'search.minRating': 'Note minimum',
    'search.location': 'Lieu',
    'search.onlyPromotions': 'Uniquement les promotions',
    'search.seeResultsCount': 'Voir {count} résultats',
    'search.searchStyle': 'Rechercher un style...',
    'search.styleGallery': 'Galerie de Styles',

    // Booking
    'booking.book': 'Réserver',
    'booking.confirmed': 'Confirmé',
    'booking.pending': 'En attente',
    'booking.cancelled': 'Annulé',
    'booking.completed': 'Terminé',
    'booking.yourBookings': 'Mes réservations',
    'booking.upcoming': 'À venir',
    'booking.past': 'Passées',
    'booking.selectService': 'Veuillez sélectionner un service',
    'booking.reservation': 'Réservation',

    // Chat
    'chat.writeMessage': 'Écrivez votre message...',
    'chat.online': 'En ligne',
    'chat.reservationConfirmed': 'Réservation confirmée ! Vous pouvez maintenant discuter.',
    'chat.willBeLate': "J'aurai un peu de retard",
    'chat.onMyWay': 'Je suis en route',
    'chat.whatTime': 'À quelle heure exactement ?',
    'chat.sendAddress': "Pouvez-vous m'envoyer l'adresse ?",

    // Coiffeur Dashboard
    'coiffeur.developActivity': 'Développez votre activité',
    'coiffeur.joinCommunity': 'Rejoignez la communauté AfroPlan Pro et boostez votre salon',
    'coiffeur.rdvManagement': 'Gestion des RDV',
    'coiffeur.manageReservations': 'Gérez facilement vos réservations',
    'coiffeur.moreClients': 'Plus de clients',
    'coiffeur.increaseVisibility': 'Augmentez votre visibilité',
    'coiffeur.statistics': 'Statistiques',
    'coiffeur.trackPerformance': 'Suivez vos performances',
    'coiffeur.payments': 'Paiements',
    'coiffeur.securePayment': 'Encaissez en toute sécurité',
    'coiffeur.readyToStart': 'Prêt à commencer ?',
    'coiffeur.registerFree': 'Inscrivez-vous gratuitement et commencez à recevoir des réservations',
    'coiffeur.createProAccount': 'Créer mon compte Pro',
    'coiffeur.needPhotoHelp': 'Besoin d\'aide pour vos photos ?',
    'coiffeur.photoHelpDesc': 'Si vous avez des difficultés pour des prises de photos professionnelles, contactez-nous et nous viendrons vous aider gratuitement !',
    'coiffeur.space': 'Espace Coiffeur',
    'coiffeur.launchActivity': 'Lancez votre activité',
    'coiffeur.createSalonDesc': 'Créez votre salon en quelques clics et recevez des réservations',
    'coiffeur.createMySalon': 'Créer mon salon',
    'coiffeur.createSalonCTA': 'Configurez votre salon et commencez à recevoir des réservations dès maintenant',
    'coiffeur.greeting.morning': 'Bonjour',
    'coiffeur.greeting.afternoon': 'Bon après-midi',
    'coiffeur.greeting.evening': 'Bonsoir',
    'coiffeur.updateError': 'Impossible de mettre à jour votre profil. Réessayez.',
    'coiffeur.monthlyRevenue': 'Revenus (mois)',
    'coiffeur.quickActions': 'Actions rapides',
    'coiffeur.manageMySalon': 'Gérer mon salon',
    'coiffeur.manageMyServices': 'Gérer mes services',
    'coiffeur.seeReservations': 'Voir les réservations',
    'coiffeur.clientMessages': 'Messages clients',
    'coiffeur.upcomingAppointments': 'Prochains rendez-vous',

    // Profile
    'profile.myProfile': 'Mon profil',
    'profile.settings': 'Paramètres',
    'profile.language': 'Langue',
    'profile.notifications': 'Notifications',
    'profile.help': 'Aide',
    'profile.about': 'À propos',
    'profile.loginMessage': 'Connectez-vous pour gérer votre profil, vos rendez-vous et vos messages',
    'profile.coiffeurMode': 'Mode Coiffeur',
    'profile.switchToCoiffeur': 'Basculer vers l\'espace coiffeur',
    'profile.myAppointments': 'Mes rendez-vous',
    'profile.messages': 'Messages',
    'profile.account': 'Compte',
    'profile.logoutButton': 'Se déconnecter',

    // Favorites
    'favorites.title': 'Favoris',
    'favorites.yourFavorites': 'Vos favoris',
    'favorites.loginMessage': 'Connectez-vous pour sauvegarder vos salons et styles préférés',
    'favorites.subtitle': 'Vos salons et styles préférés',
    'favorites.salons': 'Salons',

    // Hairstyles
    'hairstyle.tresses': 'Tresses',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Coupe',
    'hairstyle.soins': 'Soins',
    'hairstyle.coloration': 'Coloration',
    'hairstyle.tissage': 'Tissage',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',

    // Role selection
    'role.chooseSpace': 'Choisissez votre espace',
    'role.clientSpace': 'Espace Client',
    'role.clientSubtitle': 'Trouve ton coiffeur afro et réserve en quelques clics',
    'role.coiffeurSpace': 'Espace Coiffeur',
    'role.coiffeurSubtitle': 'Gère tes rendez-vous et développe ton activité',
    'role.start': 'Commencer',
    'role.access': 'Accéder',
    'role.tagline': 'La coiffure afro, réinventée.',
    'role.trust': 'Déjà +100 coiffeurs nous font confiance.',
    'role.switchRole': 'Changer de parcours',
    'role.switchToClient': 'Passer en mode Client',
    'role.switchToCoiffeur': 'Passer en mode Coiffeur',

    // Onboarding
    'onboarding.slide1Title': 'Des coiffeurs passionnés',
    'onboarding.slide1Subtitle': 'Spécialistes des cheveux afro près de chez toi',
    'onboarding.slide2Title': 'Trouve ton style parfait',
    'onboarding.slide2Subtitle': 'Des centaines de coiffures afro à portée de main',
    'onboarding.slide3Title': 'Réserve en quelques clics',
    'onboarding.slide3Subtitle': 'Simple, rapide et sans stress',
    'onboarding.touchToContinue': 'Touchez l\'écran pour continuer',

    // Geolocation
    'geo.enableLocation': 'Activer la géolocalisation',
    'geo.locationDesc': 'Pour trouver les salons près de chez toi',
    'geo.permissionDenied': 'Permission de localisation refusée',
    'geo.maxDistance': 'Distance maximum',
    'geo.nearbyRadius': 'Rayon de recherche',

    // Checkout & Payment
    'checkout.title': 'Paiement',
    'checkout.secure': 'Sécurisé',
    'checkout.yourBooking': 'Votre réservation',
    'checkout.paymentMethod': 'Moyen de paiement',
    'checkout.creditCard': 'Carte bancaire',
    'checkout.priceDetail': 'Détail du prix',
    'checkout.servicePrice': 'Prix du service',
    'checkout.depositNow': 'Acompte à payer maintenant',
    'checkout.depositInfo': 'Cet acompte confirme votre réservation et sera déduit du prix total. Le reste sera payé directement au salon le jour du rendez-vous.',
    'checkout.remainingAtSalon': 'Reste à payer au salon',
    'checkout.securePayment': 'Paiement sécurisé en 2 étapes',
    'checkout.step1': 'Payez l\'acompte maintenant',
    'checkout.step2': 'Réglez le reste au salon',
    'checkout.payDeposit': 'Payer l\'acompte de',
    'checkout.payFull': 'Payer la totalité',
    'checkout.paymentSuccess': 'Paiement réussi !',
    'checkout.paymentSuccessDesc': 'Votre réservation est confirmée.',
    'checkout.paymentError': 'Erreur de paiement',
    'checkout.paymentErrorDesc': 'Une erreur est survenue. Veuillez réessayer.',
    'checkout.viewBooking': 'Voir ma réservation',
    'checkout.termsNotice': 'Paiement sécurisé par Stripe. En payant, vous acceptez nos conditions d\'utilisation.',
    'checkout.choosePaymentType': 'Choisir le type de paiement',
    'checkout.depositOnly': 'Acompte uniquement',
    'checkout.fullPayment': 'Paiement intégral',
    'checkout.commission': 'Commission AfroPlan',

    // Salon Registration & Detail
    'salon.photos': 'Photos du salon',
    'salon.addPhotos': 'Ajoutez jusqu\'à {max} photos de votre salon',
    'salon.info': 'Informations du salon',
    'salon.name': 'Nom du salon',
    'salon.description': 'Description',
    'salon.phone': 'Téléphone',
    'salon.email': 'Email',
    'salon.emailHint': 'L\'email est celui de votre compte et ne peut pas être modifié',
    'salon.location': 'Localisation',
    'salon.address': 'Adresse',
    'salon.city': 'Ville',
    'salon.postalCode': 'Code postal',
    'salon.specialties': 'Spécialités de coiffure afro',
    'salon.selectedSpecialties': 'sélectionnées',
    'salon.selectSpecialties': 'Sélectionnez vos spécialités ({count} sélectionnées)',
    'salon.save': 'Enregistrer les modifications',
    'salon.saving': 'Enregistrement...',
    'salon.saved': 'Salon enregistré !',
    'salon.savedDesc': 'Les informations de votre salon ont été sauvegardées.',
    'salon.openingHours': 'Horaires d\'ouverture',
    'salon.homeService': 'Service à domicile',
    'salon.homeServiceDesc': 'Proposez-vous un service à domicile ?',
    'salon.homeServiceFee': 'Frais de déplacement',
    'salon.homeServiceTravel': 'Je me déplace chez les clients',
    'salon.connectLogin': 'Se connecter',
    'salon.createPro': 'Créer un compte Pro',
    'salon.mySalon': 'Mon salon',
    'salon.loginMessage': 'Connectez-vous pour créer et gérer votre salon, ajouter vos photos et spécialités',
    'salon.limitReached': 'Limite atteinte',
    'salon.maxPhotosMessage': 'Vous ne pouvez ajouter que {max} photos maximum.',
    'salon.permissionRequired': 'Permission requise',
    'salon.galleryPermission': 'Vous devez autoriser l\'accès à la galerie pour ajouter des photos.',
    'salon.cameraPermission': 'Vous devez autoriser l\'accès à la caméra pour prendre des photos.',
    'salon.deletePhoto': 'Supprimer la photo',
    'salon.deletePhotoConfirm': 'Voulez-vous vraiment supprimer cette photo ?',
    'salon.notFound': 'Salon introuvable',
    'salon.notFoundDesc': 'Ce salon n\'existe pas ou a été supprimé.',
    'salon.about': 'À propos',
    'salon.services': 'Services',
    'salon.gallery': 'Galerie',
    'salon.noServices': 'Aucun service disponible',
    'salon.selectServiceHint': 'Sélectionnez un service',
    'salon.call': 'Appeler',
    'salon.directions': 'Itinéraire',
    'salon.photoChoice': 'Ajouter une photo',
    'salon.takePhoto': 'Prendre une photo',
    'salon.chooseFromGallery': 'Choisir depuis la galerie',
    'salon.namePlaceholder': 'Ex: Afro Beauty Paris',
    'salon.descriptionPlaceholder': 'Décrivez votre salon, vos spécialités...',
    'salon.phonePlaceholder': 'Ex: +33 6 12 34 56 78',
    'salon.addressPlaceholder': 'Ex: 123 Rue de la Paix',
    'salon.cityPlaceholder': 'Ex: Paris',

    // Tabs
    'tab.home': 'Accueil',
    'tab.styles': 'Styles',
    'tab.search': 'Recherche',
    'tab.favorites': 'Favoris',
    'tab.profile': 'Profil',

    // Days
    'day.monday': 'Lundi',
    'day.tuesday': 'Mardi',
    'day.wednesday': 'Mercredi',
    'day.thursday': 'Jeudi',
    'day.friday': 'Vendredi',
    'day.saturday': 'Samedi',
    'day.sunday': 'Dimanche',
  },

  en: {
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.next': 'Next',
    'common.back': 'Back',
    'common.search': 'Search',
    'common.seeAll': 'See all',
    'common.seeLess': 'See less',
    'common.seeResults': 'See results',
    'common.add': 'Add',
    'common.errorOccurred': 'An error occurred. Please try again.',
    'common.available': 'Available',
    'common.open': 'Open',
    'common.closed': 'Closed',
    'common.verified': 'Verified',
    'common.results': 'result(s)',
    'common.found': 'found',
    'common.both': 'Both',
    'common.reset': 'Reset',
    'common.support': 'Support',
    'common.terms': 'Terms',
    'common.privacy': 'Privacy',
    'common.joinUs': 'Join us',
    'common.copyright': '© 2025 AfroPlan. All rights reserved.',
    'common.today': 'Today',
    'common.pending': 'Pending',
    'common.confirmed': 'Confirmed',
    'common.start': 'Get started',
    'common.newMessages': '{count} new',
    'common.warning': 'Warning',
    'auth.login': 'Login',
    'auth.register': 'Sign up',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.loginRequired': 'Login required',
    'auth.loginRequiredMessage': 'You must be logged in to make a payment.',
    'auth.loginRequiredBooking': 'You must be logged in to book.',
    'auth.loginRequiredFavorite': 'You must be logged in to add to favorites.',
    'auth.loginToSee': 'Log in to see salon details and book',
    'auth.createAccount': 'Create account',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': 'No account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.logoutConfirm': 'Are you sure you want to log out?',
    'auth.logoutAction': 'Log out',
    'home.welcome': 'Welcome to AfroPlan',
    'home.hello': 'Hello {name}',
    'home.readyForHairstyle': 'Ready for a new hairstyle?',
    'home.searchSalon': 'Search my salon / hairstylist',
    'home.searchSubtitle': 'Find the style that suits you',
    'home.promotions': 'Current offers',
    'home.hairstyles': 'Hairstyles',
    'home.nearbyCoiffeurs': 'Nearby hairstylists',
    'home.popularSalons': 'Popular salons',
    'home.tipsAndInspiration': 'Tips & Inspiration',
    'home.areYouCoiffeur': 'Are you a hairstylist?',
    'home.joinAfroPlanPro': 'Join AfroPlan Pro and grow your business',
    'home.discoverPro': 'Discover AfroPlan Pro',
    'search.findCoiffeur': 'Easily find your afro hairstylist',
    'search.quickQuestions': 'A few quick questions to suggest the best salons for your needs.',
    'search.chooseStyle': 'Choose your hairstyle',
    'search.whatStyle': 'What style would you like?',
    'search.quickFilter': 'Quick filter',
    'search.optional': 'Optional - Refine your search',
    'search.hairType': 'Hair type',
    'search.whereCoiffeur': 'Where would you like to get your hair done?',
    'search.inSalon': 'In salon',
    'search.atHome': 'At home',
    'search.goToSalon': 'Go to the salon',
    'search.coiffeurComesHome': 'The hairstylist comes to you',
    'search.budgetDistance': 'Budget & Distance',
    'search.maxBudget': 'Maximum budget',
    'search.maxDistance': 'Maximum distance',
    'search.showAllSalons': 'I want to see all salons (ignore filters)',
    'search.paymentInfo': 'You can choose to pay the full amount or a deposit when booking.',
    'search.canGoBack': 'You can go back at any time',
    'search.quickPay': 'Quick pay',
    'search.placeholder': 'Salon, hairstylist, style...',
    'search.title': 'Search',
    'search.advancedFilters': 'Advanced filters',
    'search.maxDistanceLabel': 'Maximum distance',
    'search.minRating': 'Minimum rating',
    'search.location': 'Location',
    'search.onlyPromotions': 'Promotions only',
    'search.seeResultsCount': 'See {count} results',
    'search.searchStyle': 'Search a style...',
    'search.styleGallery': 'Style Gallery',
    'booking.book': 'Book',
    'booking.confirmed': 'Confirmed',
    'booking.pending': 'Pending',
    'booking.cancelled': 'Cancelled',
    'booking.completed': 'Completed',
    'booking.yourBookings': 'My bookings',
    'booking.upcoming': 'Upcoming',
    'booking.past': 'Past',
    'booking.selectService': 'Please select a service',
    'booking.reservation': 'Reservation',
    'chat.writeMessage': 'Write your message...',
    'chat.online': 'Online',
    'chat.reservationConfirmed': 'Booking confirmed! You can now chat.',
    'chat.willBeLate': "I'll be a bit late",
    'chat.onMyWay': "I'm on my way",
    'chat.whatTime': 'What time exactly?',
    'chat.sendAddress': 'Can you send me the address?',
    'coiffeur.developActivity': 'Grow your business',
    'coiffeur.joinCommunity': 'Join the AfroPlan Pro community and boost your salon',
    'coiffeur.rdvManagement': 'Booking management',
    'coiffeur.manageReservations': 'Easily manage your bookings',
    'coiffeur.moreClients': 'More clients',
    'coiffeur.increaseVisibility': 'Increase your visibility',
    'coiffeur.statistics': 'Statistics',
    'coiffeur.trackPerformance': 'Track your performance',
    'coiffeur.payments': 'Payments',
    'coiffeur.securePayment': 'Get paid securely',
    'coiffeur.readyToStart': 'Ready to start?',
    'coiffeur.registerFree': 'Sign up for free and start receiving bookings',
    'coiffeur.createProAccount': 'Create my Pro account',
    'coiffeur.needPhotoHelp': 'Need help with your photos?',
    'coiffeur.photoHelpDesc': 'If you have trouble taking professional photos, contact us and we\'ll come help you for free!',
    'coiffeur.space': 'Hairstylist Space',
    'coiffeur.launchActivity': 'Launch your business',
    'coiffeur.createSalonDesc': 'Create your salon in a few clicks and start receiving bookings',
    'coiffeur.createMySalon': 'Create my salon',
    'coiffeur.createSalonCTA': 'Set up your salon and start receiving bookings now',
    'coiffeur.greeting.morning': 'Good morning',
    'coiffeur.greeting.afternoon': 'Good afternoon',
    'coiffeur.greeting.evening': 'Good evening',
    'coiffeur.updateError': 'Unable to update your profile. Please try again.',
    'coiffeur.monthlyRevenue': 'Revenue (month)',
    'coiffeur.quickActions': 'Quick actions',
    'coiffeur.manageMySalon': 'Manage my salon',
    'coiffeur.manageMyServices': 'Manage my services',
    'coiffeur.seeReservations': 'See reservations',
    'coiffeur.clientMessages': 'Client messages',
    'coiffeur.upcomingAppointments': 'Upcoming appointments',
    'profile.myProfile': 'My profile',
    'profile.settings': 'Settings',
    'profile.language': 'Language',
    'profile.notifications': 'Notifications',
    'profile.help': 'Help',
    'profile.about': 'About',
    'profile.loginMessage': 'Log in to manage your profile, appointments and messages',
    'profile.coiffeurMode': 'Hairstylist Mode',
    'profile.switchToCoiffeur': 'Switch to hairstylist space',
    'profile.myAppointments': 'My appointments',
    'profile.messages': 'Messages',
    'profile.account': 'Account',
    'profile.logoutButton': 'Log out',
    'favorites.title': 'Favorites',
    'favorites.yourFavorites': 'Your favorites',
    'favorites.loginMessage': 'Log in to save your favorite salons and styles',
    'favorites.subtitle': 'Your favorite salons and styles',
    'favorites.salons': 'Salons',
    'hairstyle.tresses': 'Braids',
    'hairstyle.locks': 'Locs',
    'hairstyle.coupe': 'Cut',
    'hairstyle.soins': 'Care',
    'hairstyle.coloration': 'Coloring',
    'hairstyle.tissage': 'Weave',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',
    'role.chooseSpace': 'Choose your space',
    'role.clientSpace': 'Client Space',
    'role.clientSubtitle': 'Find your afro hairstylist and book in a few clicks',
    'role.coiffeurSpace': 'Hairstylist Space',
    'role.coiffeurSubtitle': 'Manage your appointments and grow your business',
    'role.start': 'Get started',
    'role.access': 'Access',
    'role.tagline': 'Afro hairstyling, reinvented.',
    'role.trust': 'Already 100+ hairstylists trust us.',
    'role.switchRole': 'Switch path',
    'role.switchToClient': 'Switch to Client mode',
    'role.switchToCoiffeur': 'Switch to Hairstylist mode',
    'onboarding.slide1Title': 'Passionate hairstylists',
    'onboarding.slide1Subtitle': 'Afro hair specialists near you',
    'onboarding.slide2Title': 'Find your perfect style',
    'onboarding.slide2Subtitle': 'Hundreds of afro hairstyles at your fingertips',
    'onboarding.slide3Title': 'Book in a few clicks',
    'onboarding.slide3Subtitle': 'Simple, fast and stress-free',
    'onboarding.touchToContinue': 'Tap to continue',
    'geo.enableLocation': 'Enable location',
    'geo.locationDesc': 'To find salons near you',
    'geo.permissionDenied': 'Location permission denied',
    'geo.maxDistance': 'Maximum distance',
    'geo.nearbyRadius': 'Search radius',
    'checkout.title': 'Payment',
    'checkout.secure': 'Secure',
    'checkout.yourBooking': 'Your booking',
    'checkout.paymentMethod': 'Payment method',
    'checkout.creditCard': 'Credit card',
    'checkout.priceDetail': 'Price detail',
    'checkout.servicePrice': 'Service price',
    'checkout.depositNow': 'Deposit to pay now',
    'checkout.depositInfo': 'This deposit confirms your booking and will be deducted from the total price. The rest is paid directly at the salon on appointment day.',
    'checkout.remainingAtSalon': 'Remaining to pay at salon',
    'checkout.securePayment': 'Secure 2-step payment',
    'checkout.step1': 'Pay the deposit now',
    'checkout.step2': 'Pay the rest at the salon',
    'checkout.payDeposit': 'Pay deposit of',
    'checkout.payFull': 'Pay in full',
    'checkout.paymentSuccess': 'Payment successful!',
    'checkout.paymentSuccessDesc': 'Your booking is confirmed.',
    'checkout.paymentError': 'Payment error',
    'checkout.paymentErrorDesc': 'An error occurred. Please try again.',
    'checkout.viewBooking': 'View my booking',
    'checkout.termsNotice': 'Secure payment by Stripe. By paying, you accept our terms of use.',
    'checkout.choosePaymentType': 'Choose payment type',
    'checkout.depositOnly': 'Deposit only',
    'checkout.fullPayment': 'Full payment',
    'checkout.commission': 'AfroPlan commission',
    'salon.photos': 'Salon photos',
    'salon.addPhotos': 'Add up to {max} photos of your salon',
    'salon.info': 'Salon information',
    'salon.name': 'Salon name',
    'salon.description': 'Description',
    'salon.phone': 'Phone',
    'salon.email': 'Email',
    'salon.emailHint': 'Email is from your account and cannot be changed',
    'salon.location': 'Location',
    'salon.address': 'Address',
    'salon.city': 'City',
    'salon.postalCode': 'Postal code',
    'salon.specialties': 'Afro hairstyling specialties',
    'salon.selectedSpecialties': 'selected',
    'salon.selectSpecialties': 'Select your specialties ({count} selected)',
    'salon.save': 'Save changes',
    'salon.saving': 'Saving...',
    'salon.saved': 'Salon saved!',
    'salon.savedDesc': 'Your salon information has been saved.',
    'salon.openingHours': 'Opening hours',
    'salon.homeService': 'Home service',
    'salon.homeServiceDesc': 'Do you offer home service?',
    'salon.homeServiceFee': 'Travel fee',
    'salon.homeServiceTravel': 'I travel to clients',
    'salon.connectLogin': 'Log in',
    'salon.createPro': 'Create Pro account',
    'salon.mySalon': 'My salon',
    'salon.loginMessage': 'Log in to create and manage your salon, add photos and specialties',
    'salon.limitReached': 'Limit reached',
    'salon.maxPhotosMessage': 'You can add up to {max} photos.',
    'salon.permissionRequired': 'Permission required',
    'salon.galleryPermission': 'You must allow gallery access to add photos.',
    'salon.cameraPermission': 'You must allow camera access to take photos.',
    'salon.deletePhoto': 'Delete photo',
    'salon.deletePhotoConfirm': 'Do you really want to delete this photo?',
    'salon.notFound': 'Salon not found',
    'salon.notFoundDesc': 'This salon does not exist or has been deleted.',
    'salon.about': 'About',
    'salon.services': 'Services',
    'salon.gallery': 'Gallery',
    'salon.noServices': 'No services available',
    'salon.selectServiceHint': 'Select a service',
    'salon.call': 'Call',
    'salon.directions': 'Directions',
    'salon.photoChoice': 'Add a photo',
    'salon.takePhoto': 'Take a photo',
    'salon.chooseFromGallery': 'Choose from gallery',
    'salon.namePlaceholder': 'E.g.: Afro Beauty Paris',
    'salon.descriptionPlaceholder': 'Describe your salon, specialties...',
    'salon.phonePlaceholder': 'E.g.: +33 6 12 34 56 78',
    'salon.addressPlaceholder': 'E.g.: 123 Main Street',
    'salon.cityPlaceholder': 'E.g.: Paris',
    'tab.home': 'Home',
    'tab.styles': 'Styles',
    'tab.search': 'Search',
    'tab.favorites': 'Favorites',
    'tab.profile': 'Profile',
    'day.monday': 'Monday',
    'day.tuesday': 'Tuesday',
    'day.wednesday': 'Wednesday',
    'day.thursday': 'Thursday',
    'day.friday': 'Friday',
    'day.saturday': 'Saturday',
    'day.sunday': 'Sunday',
  },

  de: {
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.next': 'Weiter',
    'common.back': 'Zurück',
    'common.search': 'Suchen',
    'common.seeAll': 'Alle anzeigen',
    'common.seeLess': 'Weniger anzeigen',
    'common.seeResults': 'Ergebnisse anzeigen',
    'common.add': 'Hinzufügen',
    'common.errorOccurred': 'Ein Fehler ist aufgetreten. Bitte versuche es erneut.',
    'common.available': 'Verfügbar',
    'common.open': 'Geöffnet',
    'common.closed': 'Geschlossen',
    'common.verified': 'Verifiziert',
    'common.copyright': '© 2025 AfroPlan. Alle Rechte vorbehalten.',
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.logout': 'Abmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.noAccount': 'Kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'auth.loginRequired': 'Anmeldung erforderlich',
    'home.welcome': 'Willkommen bei AfroPlan',
    'home.hello': 'Hallo {name}',
    'home.readyForHairstyle': 'Bereit für eine neue Frisur?',
    'home.searchSalon': 'Meinen Salon / Friseur suchen',
    'home.searchSubtitle': 'Finde den Stil, der zu dir passt',
    'home.promotions': 'Aktuelle Angebote',
    'home.hairstyles': 'Frisuren',
    'home.nearbyCoiffeurs': 'Friseure in der Nähe',
    'home.popularSalons': 'Beliebte Salons',
    'home.tipsAndInspiration': 'Tipps & Inspiration',
    'home.areYouCoiffeur': 'Bist du Friseur(in)?',
    'home.joinAfroPlanPro': 'Tritt AfroPlan Pro bei und entwickle dein Geschäft',
    'home.discoverPro': 'AfroPlan Pro entdecken',
    'hairstyle.tresses': 'Zöpfe',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Schnitt',
    'hairstyle.soins': 'Pflege',
    'hairstyle.coloration': 'Färbung',
    'hairstyle.tissage': 'Weave',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',
    'salon.openingHours': 'Öffnungszeiten',
    'salon.homeService': 'Hausbesuch',
    'salon.homeServiceDesc': 'Bieten Sie Hausbesuche an?',
    'salon.homeServiceTravel': 'Ich fahre zu Kunden',
    'tab.home': 'Startseite',
    'tab.styles': 'Stile',
    'tab.search': 'Suche',
    'tab.favorites': 'Favoriten',
    'tab.profile': 'Profil',
    'day.monday': 'Montag',
    'day.tuesday': 'Dienstag',
    'day.wednesday': 'Mittwoch',
    'day.thursday': 'Donnerstag',
    'day.friday': 'Freitag',
    'day.saturday': 'Samstag',
    'day.sunday': 'Sonntag',
  },

  es: {
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.next': 'Siguiente',
    'common.back': 'Atrás',
    'common.search': 'Buscar',
    'common.seeAll': 'Ver todo',
    'common.seeLess': 'Ver menos',
    'common.seeResults': 'Ver resultados',
    'common.add': 'Añadir',
    'common.errorOccurred': 'Ha ocurrido un error. Inténtelo de nuevo.',
    'common.available': 'Disponible',
    'common.open': 'Abierto',
    'common.closed': 'Cerrado',
    'common.verified': 'Verificado',
    'common.copyright': '© 2025 AfroPlan. Todos los derechos reservados.',
    'auth.login': 'Iniciar sesión',
    'auth.register': 'Registrarse',
    'auth.logout': 'Cerrar sesión',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.loginRequired': 'Inicio de sesión requerido',
    'home.welcome': 'Bienvenido a AfroPlan',
    'home.hello': 'Hola {name}',
    'home.readyForHairstyle': '¿Listo para un nuevo peinado?',
    'home.searchSalon': 'Buscar mi salón / estilista',
    'home.searchSubtitle': 'Encuentra el estilo que te queda',
    'home.promotions': 'Ofertas actuales',
    'home.hairstyles': 'Estilos de peinado',
    'home.nearbyCoiffeurs': 'Estilistas cercanos',
    'home.popularSalons': 'Salones populares',
    'home.tipsAndInspiration': 'Consejos e Inspiración',
    'home.areYouCoiffeur': '¿Eres estilista?',
    'home.joinAfroPlanPro': 'Únete a AfroPlan Pro y haz crecer tu negocio',
    'home.discoverPro': 'Descubrir AfroPlan Pro',
    'hairstyle.tresses': 'Trenzas',
    'hairstyle.locks': 'Locks',
    'hairstyle.coupe': 'Corte',
    'hairstyle.soins': 'Tratamientos',
    'hairstyle.coloration': 'Coloración',
    'hairstyle.tissage': 'Tejido',
    'hairstyle.cornrows': 'Cornrows',
    'hairstyle.afro': 'Afro',
    'salon.openingHours': 'Horario de apertura',
    'salon.homeService': 'Servicio a domicilio',
    'salon.homeServiceDesc': '¿Ofreces servicio a domicilio?',
    'salon.homeServiceTravel': 'Me desplazo a los clientes',
    'tab.home': 'Inicio',
    'tab.styles': 'Estilos',
    'tab.search': 'Búsqueda',
    'tab.favorites': 'Favoritos',
    'tab.profile': 'Perfil',
    'day.monday': 'Lunes',
    'day.tuesday': 'Martes',
    'day.wednesday': 'Miércoles',
    'day.thursday': 'Jueves',
    'day.friday': 'Viernes',
    'day.saturday': 'Sábado',
    'day.sunday': 'Domingo',
  },
};

const LANGUAGE_STORAGE_KEY = '@afroplan_language';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr');
  const [isReady, setIsReady] = useState(false);

  // Load saved language on mount, or detect device locale
  useEffect(() => {
    loadSavedLanguage();
  }, []);

  const loadSavedLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLanguage && ['fr', 'en', 'de', 'es'].includes(savedLanguage)) {
        setLanguageState(savedLanguage as Language);
      } else {
        // Premier lancement : détecter la langue du téléphone
        const deviceLang = getDeviceLocale();
        setLanguageState(deviceLang);
        await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, deviceLang);
      }
    } catch {
      // Fallback silencieux
    } finally {
      setIsReady(true);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
      setLanguageState(lang);
    } catch {
      // Fallback silencieux
    }
  };

  // Translation function with parameter interpolation
  const t = useCallback((key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || translations['fr'][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
      });
    }
    return text;
  }, [language]);

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        languages: LANGUAGES,
        isReady,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
